### ISSUE TITLE
Standardise casing

### ISSUE THREAD

**Issue by ArtOfCode-** [AWegnerGitHub/helios#1]
Case in point: response from `/notifications`:

    {"items": [], "numItems": 0, "message": "", "error_type": null}

Instead of `numItems` and `error_type`, let's standardise on either camelCase or snake_case. I'd suggest snake_case personally, to match both metasmoke and Smokey standards, but it doesn't matter a huge amount.

**Comment by AWegnerGitHub** [comment]
This needs to be fixed on blacklist end points too
